### ISSUE TITLE
Pod upload error: Could not locate bindings file

### ISSUE THREAD

**Issue by Ossadtchii** [codius/codius#40]
Installing Codius and attempting to upload a pod trows the following error:
```
/usr/lib/node_modules/codius/node_modules/bindings/bindings.js:93
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/codius/node_modules/leveldown/build/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/build/Release/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/Debug/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/out/Release/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/Release/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/build/default/leveldown.node
 → /usr/lib/node_modules/codius/node_modules/leveldown/compiled/10.4.1/linux/x64/leveldown.node
    at bindings (/usr/lib/node_modules/codius/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/codius/node_modules/leveldown/leveldown.js:3:36)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/codius/node_modules/level/level.js:1:44)
```

However, navigating to `/usr/lib/node_modules/codius/node_modules/` and executing `npm rebuild` seems to fix the issue.

Hope this helps.

**Comment by traviscrist** [comment]
Thanks for the details, on the original npm install did you see lots of errors? 

This usually seems to happen when installing as root without the `--unsafe-perm` flag provided. A clean install or rebuild seems to fix it. Ill add this to one of the wiki docs to help others debug.

**Comment by Ossadtchii** [comment]
Not that I can recall. I did install using `sudo npm install -g codius --unsafe-perm` as `npm install -g codius` was throwing `user "root" does not have permission to access the dev dir `

**Comment by gonzocode** [comment]
What version of Node are you running ?

**Comment by Ossadtchii** [comment]
v 10.4.1

**Comment by traviscrist** [comment]
Moved away from LevelDB in the Codius CLI 3.0.0, closing this since the bindings issue should now no longer occur.
